create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text,
  bio text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  image_url text not null,
  caption text,
  created_at timestamptz not null default now()
);

create table if not exists public.likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;
alter table public.follows enable row level security;

create policy "profiles are public" on public.profiles for select using (true);
create policy "users can create own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users can update own profile" on public.profiles for update using (auth.uid() = id);

create policy "posts are public" on public.posts for select using (true);
create policy "users can create own posts" on public.posts for insert with check (auth.uid() = user_id);
create policy "users can update own posts" on public.posts for update using (auth.uid() = user_id);
create policy "users can delete own posts" on public.posts for delete using (auth.uid() = user_id);

create policy "likes are public" on public.likes for select using (true);
create policy "users can like as themselves" on public.likes for insert with check (auth.uid() = user_id);
create policy "users can remove own likes" on public.likes for delete using (auth.uid() = user_id);

create policy "comments are public" on public.comments for select using (true);
create policy "users can create own comments" on public.comments for insert with check (auth.uid() = user_id);
create policy "users can delete own comments" on public.comments for delete using (auth.uid() = user_id);

create policy "follows are public" on public.follows for select using (true);
create policy "users can follow as themselves" on public.follows for insert with check (auth.uid() = follower_id);
create policy "users can unfollow as themselves" on public.follows for delete using (auth.uid() = follower_id);

create index if not exists posts_user_created_idx on public.posts(user_id, created_at desc);
create index if not exists comments_post_created_idx on public.comments(post_id, created_at desc);
