import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import 'bootstrap/dist/css/bootstrap.min.css';
import {Home,Search,PlusSquare,Heart,User,Bookmark,Send,MoreHorizontal,Compass,Play,MessageCircle} from 'lucide-react';
import './styles.css';

const stories=[['gokul','https://i.pravatar.cc/100?img=12'],['maya','https://i.pravatar.cc/100?img=47'],['arjun','https://i.pravatar.cc/100?img=13'],['sara','https://i.pravatar.cc/100?img=32'],['leo','https://i.pravatar.cc/100?img=68'],['nisha','https://i.pravatar.cc/100?img=44']];
const posts=[
 {id:1,user:'gokul',avatar:'https://i.pravatar.cc/100?img=12',place:'Chennai, India',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85',caption:'Chasing light and building something new.',likes:128},
 {id:2,user:'maya',avatar:'https://i.pravatar.cc/100?img=47',place:'Coimbatore',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=80&sat=-20',caption:'Weekend reset ✨',likes:96},
 {id:3,user:'arjun',avatar:'https://i.pravatar.cc/100?img=13',place:'Bengaluru',image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1000&q=85',caption:'Quiet places, loud ideas.',likes:214}
];
function App(){const [tab,setTab]=useState('home');const [liked,setLiked]=useState({});const [saved,setSaved]=useState({});const [query,setQuery]=useState('');const [showCreate,setShowCreate]=useState(false);const [following,setFollowing]=useState(false);
 const nav=(t)=>setTab(t);
 return <div className="app"><aside className="sidebar"><div className="brand">InstaClone</div><Nav icon={<Home/>} label="Home" active={tab==='home'} onClick={()=>nav('home')}/><Nav icon={<Search/>} label="Search" active={tab==='search'} onClick={()=>nav('search')}/><Nav icon={<Compass/>} label="Explore" active={tab==='explore'} onClick={()=>nav('explore')}/><Nav icon={<Play/>} label="Reels" active={tab==='reels'} onClick={()=>nav('reels')}/><Nav icon={<MessageCircle/>} label="Messages" active={tab==='messages'} onClick={()=>nav('messages')}/><Nav icon={<Heart/>} label="Notifications" active={tab==='notifications'} onClick={()=>nav('notifications')}/><Nav icon={<PlusSquare/>} label="Create" onClick={()=>setShowCreate(true)}/><Nav icon={<User/>} label="Profile" active={tab==='profile'} onClick={()=>nav('profile')}/></aside>
 <main><header className="mobileHeader"><b>InstaClone</b><div><Heart size={22}/><Send size={22}/></div></header>
 {tab==='home'&&<HomeView liked={liked} setLiked={setLiked} saved={saved} setSaved={setSaved}/>} {tab==='search'&&<SearchView query={query} setQuery={setQuery}/>} {tab==='explore'&&<Explore/>} {tab==='reels'&&<Reels/>} {tab==='messages'&&<Messages/>} {tab==='notifications'&&<Notifications/>} {tab==='profile'&&<Profile following={following} setFollowing={setFollowing}/>}</main>
 <nav className="bottom"><Nav icon={<Home/>} active={tab==='home'} onClick={()=>nav('home')}/><Nav icon={<Search/>} active={tab==='search'} onClick={()=>nav('search')}/><Nav icon={<PlusSquare/>} onClick={()=>setShowCreate(true)}/><Nav icon={<Play/>} active={tab==='reels'} onClick={()=>nav('reels')}/><Nav icon={<User/>} active={tab==='profile'} onClick={()=>nav('profile')}/></nav>
 {showCreate&&<div className="modal" onClick={()=>setShowCreate(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><h2>Create new post</h2><div className="upload">＋<span>Drag photos and videos here</span><button className="btn btn-primary btn-sm">Choose from device</button></div><button className="close btn btn-outline-light" onClick={()=>setShowCreate(false)}>Cancel</button></div></div>}</div>}
function Nav({icon,label,active,onClick}){return <button className={'nav '+(active?'active':'')} onClick={onClick}>{icon}{label&&<span>{label}</span>}</button>}
function HomeView({liked,setLiked,saved,setSaved}){return <section className="feed"><div className="stories">{stories.map(([n,a])=><div className="story" key={n}><div className="ring"><img src={a}/></div><span>{n}</span></div>)}</div>{posts.map(p=><article className="post" key={p.id}><div className="postHead"><img src={p.avatar}/><div><b>{p.user}</b><small>{p.place}</small></div><MoreHorizontal size={20}/></div><img className="postImage" src={p.image}/><div className="actions"><div><button onClick={()=>setLiked(x=>({...x,[p.id]:!x[p.id]}))} className={liked[p.id]?'liked':''}><Heart fill={liked[p.id]?'currentColor':'none'}/></button><button><MessageCircle/></button><button><Send/></button></div><button onClick={()=>setSaved(x=>({...x,[p.id]:!x[p.id]}))} className={saved[p.id]?'saved':''}><Bookmark fill={saved[p.id]?'currentColor':'none'}/></button></div><div className="likes"><b>{p.likes+(liked[p.id]?1:0)} likes</b></div><div className="caption"><b>{p.user}</b> {p.caption}</div><button className="comments">View all comments</button></article>)}</section>}
function SearchView({query,setQuery}){return <section className="page"><input className="search form-control" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/><h2>{query?'Results':'Recent searches'}</h2><div className="searchUsers">{stories.filter(s=>!query||s[0].includes(query.toLowerCase())).map(s=><div><img src={s[1]}/><div><b>{s[0]}</b><small>Suggested for you</small></div><button className="btn btn-outline-light btn-sm">Follow</button></div>)}</div></section>}
function Explore(){return <section className="page"><h1>Explore</h1><div className="grid">{[...Array(15)].map((_,i)=><img key={i} src={`https://images.unsplash.com/photo-${['1500534623283-312aade485b7','1519608487953-e999c86e7455','1493246507139-91e8fad9978e','1501785888041-af3ef285b470','1519681393784-d120267933ba'][i%5]}?auto=format&fit=crop&w=600&q=80`}/>)}</div></section>}
function Reels(){return <section className="page"><h1>Reels</h1><div className="reels"><div className="reel"><img src="https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80"/><div className="reelText"><b>@gokul</b><span>Build. Ship. Repeat. 🚀</span></div><Play className="play" fill="white"/></div></div></section>}
function Messages(){return <section className="page"><h1>Messages</h1>{stories.map(s=><div className="message"><img src={s[1]}/><div><b>{s[0]}</b><span>Tap to start chatting</span></div><Send size={18}/></div>)}</section>}
function Notifications(){return <section className="page"><h1>Notifications</h1>{['maya liked your post','arjun started following you','sara mentioned you in a comment','leo liked your reel'].map((x,i)=><div className="notification"><img src={stories[i][1]}/><span>{x}</span><button className="btn btn-outline-light btn-sm">View</button></div>)}</section>}
function Profile({following,setFollowing}){return <section className="page profile"><div className="profileTop"><img className="profileAvatar" src="https://i.pravatar.cc/180?img=12"/><div><h1>gokul</h1><div className="stats"><b>24 <span>posts</span></b><b>1.2K <span>followers</span></b><b>486 <span>following</span></b></div><p>Gokul • developer & creator<br/>Building useful things with code.</p><button className="btn btn-primary" onClick={()=>setFollowing(!following)}>{following?'Following':'Follow'}</button></div></div><div className="grid profileGrid">{posts.map(p=><img src={p.image}/>)}</div></section>}
createRoot(document.getElementById('root')).render(<App/>);
